//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHS.API.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonValidationLocalization_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonValidationLocalization_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BHS.API.Resources.CommonValidationLocalization.en", typeof(CommonValidationLocalization_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current time.
        /// </summary>
        internal static string CurrentTime {
            get {
                return ResourceManager.GetString("CurrentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program has ended.
        /// </summary>
        internal static string Ended {
            get {
                return ResourceManager.GetString("Ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if FortuneType = Points or Turns.
        /// </summary>
        internal static string FortuneType {
            get {
                return ResourceManager.GetString("FortuneType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does exist.
        /// </summary>
        internal static string IdExist {
            get {
                return ResourceManager.GetString("IdExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not exist.
        /// </summary>
        internal static string IdNotExist {
            get {
                return ResourceManager.GetString("IdNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept only 0 or 1.
        /// </summary>
        internal static string MustCorrectBitValue {
            get {
                return ResourceManager.GetString("MustCorrectBitValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must enter the correct type.
        /// </summary>
        internal static string MustCorrectType {
            get {
                return ResourceManager.GetString("MustCorrectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must equal {1}.
        /// </summary>
        internal static string MustEqual {
            get {
                return ResourceManager.GetString("MustEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must greater than {0}.
        /// </summary>
        internal static string MustGreaterThanOneParam {
            get {
                return ResourceManager.GetString("MustGreaterThanOneParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must greater than {1}.
        /// </summary>
        internal static string MustGreaterThanTwoParams {
            get {
                return ResourceManager.GetString("MustGreaterThanTwoParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must not null and not empty.
        /// </summary>
        internal static string MustNotNullAndNotEmpty {
            get {
                return ResourceManager.GetString("MustNotNullAndNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have enough point.
        /// </summary>
        internal static string NotEnoughPoint {
            get {
                return ResourceManager.GetString("NotEnoughPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not exist, has been used or has expired.
        /// </summary>
        internal static string NotExistOrUsedOrExpired {
            get {
                return ResourceManager.GetString("NotExistOrUsedOrExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program has been out of gifts.
        /// </summary>
        internal static string OutOfGifts {
            get {
                return ResourceManager.GetString("OutOfGifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are out of turns.
        /// </summary>
        internal static string OutOfTurns {
            get {
                return ResourceManager.GetString("OutOfTurns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid quantity.
        /// </summary>
        internal static string ValidQuantity {
            get {
                return ResourceManager.GetString("ValidQuantity", resourceCulture);
            }
        }
    }
}
